@startuml
!include _common_seq.iuml

left header
Created by @StefanDensow for PlantUML illustration.
endheader

' have an outside participant to make arrows for init() and run() visible
participant Boss as "Boss <&person>"

!include Concierge.iuml!PARTICIPANT

== Cyclic inclusion ==

$CALL_METHOD(Boss, Concierge, doThis)
note over Boss
Is there a Concierge.iuml?
!if %file_exists("Concierge.iuml")
YES!
!else
NO!
!endif
end note

@enduml