@startuml
!include _common_seq.iuml

left header
Created by @StefanDensow for PlantUML illustration.
endheader

' have an outside participant to make arrows for init() and run() visible
participant Boss as "Boss <&person>"

!include Concierge.iuml!PARTICIPANT

== Cyclic inclusion ==

'Without !unquoted:
'  $CALL_METHOD("Concierge", "Concierge", "doThis")
$CALL_METHOD(Concierge, Concierge, doThis)

@enduml