@startuml(id=PARTICIPANT)
participant Concierge
@enduml

@startuml(id=COMMON)
!include _common_seq.iuml
@enduml

@startuml(id=doThat)
!include Concierge.iuml!COMMON
$CALL_METHOD(Concierge, Concierge, doThis)
@enduml

@startuml(id=doThis)
!include Concierge.iuml!COMMON
$CALL_METHOD(Concierge, Concierge, doThat)
@enduml